# Generated by Django 5.1.7 on 2025-03-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_wastegenerator_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wastegeneratorgroup',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='wastegeneratorgroup',
            name='organization',
        ),
    ]
