# Generated by Django 5.1.7 on 2025-03-27 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_permission_userrole_userprofile_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='core.organization'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(choices=[('auditor', 'Auditor'), ('data_manager', 'Data Manager')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('name', 'organization')},
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('manage_commodity', 'Manage Commodity'), ('manage_entities', 'Manage Entities'), ('manage_agreements', 'Manage Agreements'), ('audit', 'Audit'), ('schedule_audit', 'Schedule Audit'), ('reports', 'Reports')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='core.userrole')),
            ],
            options={
                'unique_together': {('role', 'module')},
            },
        ),
    ]
